packages:
  - "weibo"
  - "zhihu"
  - "xhs"
  - "bilibili"
  - "qqmusic"
  - "xiaoyuzhou"
  - "x"
  - "weread"
  - "netease"
  - "douyin"
allowBuilds:
  '@vscode/vsce-sign': true
  bufferutil: true
  canvas: true
  esbuild: true
  keytar: true
  utf-8-validate: true
