/*
 * @Author: Generated by Copilot
 * @Date: 2025-11-03
 * @Description: 小红书用户主页 Drawer：展示用户头像/昵称及其已发布笔记瀑布流，可翻页加载。
 */
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Drawer, Avatar, Card, Button, Empty, Tag } from "antd";
import { UsergroupAddOutlined, TeamOutlined, LikeOutlined } from '@ant-design/icons';
import Masonry from "react-masonry-css";
import { createXhsApi } from "../api";
import { useRequest } from "../hooks/useRequest";
import XhsFeedCard from "./XhsFeedCard";
import { loaderFunc } from "../utils/loader";
import { XhsFeedRawItem } from "../../../type";

interface UserPostedDrawerProps {
  open: boolean;
  onClose: () => void;
  // 初始参数：从点击的笔记中获取 note id 作为 cursor（或空字符串），以及 user 对象里的 user_id 与 xsec_token
  initParams: {
    xsec_source?: any;
    cursor: string;
    user_id: string;
    xsec_token: string;
    user?: any;
  };
  onOpenDetail?: (raw: any) => void; // 点击用户主页里的笔记打开详情
}

const UserPostedDrawer: React.FC<UserPostedDrawerProps> = ({
  open,
  onClose,
  initParams,
  onOpenDetail,
}) => {
  const { request, messageApi, contextHolder } = useRequest();
  const apiRef = useRef(createXhsApi(request));

  const [loading, setLoading] = useState(false);
  const [cursor, setCursor] = useState(initParams.cursor);
  const [items, setItems] = useState<XhsFeedRawItem[]>([]);
  const [hasMore, setHasMore] = useState(true);
  // 使用 ref 保存最新 cursor，避免将 cursor 纳入 useCallback 依赖导致函数重建和二次请求
  const cursorRef = useRef(cursor);

  // 用户信息基础展示（初始）
  const user = initParams.user || {}; // 兼容从 note_card.user 传入
  const nickname: string = user.nick_name || user.nickname || "未知用户";
  const avatar: string | undefined = user.avatar;

  // Hover Card 详细数据
  const [hoverLoading, setHoverLoading] = useState(false);
  const [hoverError, setHoverError] = useState<string | null>(null);
  const [hoverData, setHoverData] = useState<any>(null);

  const fetchHover = useCallback(async () => {
    if (!initParams.user_id || !initParams.xsec_token) return;
    setHoverLoading(true);
    setHoverError(null);
    setHoverData(null);
    try {
      const res: any = await apiRef.current.getUserHoverCard({
        target_user_id: initParams.user_id,
        image_formats: 'jpg,webp,avif',
        xsec_source:'pc_comment',
        xsec_token: initParams.xsec_token,
      });
      // 兼容后端直接返回 data 或完整响应
      const dataLayer = res?.basic_info ? res : res?.data;
      setHoverData(dataLayer || null);
      console.log('[xhs user hover card raw] ', res);
      console.log('[xhs user hover card parsed] ', dataLayer);
    } catch (e: any) {
      setHoverError(e?.message || '用户信息加载失败');
    } finally {
      setHoverLoading(false);
    }
  }, [initParams.user_id, initParams.xsec_token]);

  const fetchPosted = useCallback(
    async (reset: boolean = false, nextCursor?: string) => {
      if (!initParams.user_id || !initParams.xsec_token) return;
      const useCursor = reset
        ? nextCursor ?? ""
        : nextCursor ?? cursorRef.current;
      setLoading(true);
      try {
        const res: any = await apiRef.current.getUserPosted({
          user_id: initParams.user_id,
          cursor: useCursor,
          xsec_token: initParams.xsec_token,
          xsec_source: initParams.xsec_source,
        });
        const incoming: XhsFeedRawItem[] = res?.items || [];
        setItems((prev) => (reset ? incoming : [...prev, ...incoming]));
        const newCursor = res?.cursor || "";
        setCursor(newCursor);
        cursorRef.current = newCursor; // 同步 ref
        setHasMore(!!res?.has_more);
      } catch (e) {
        console.error("[xhs user posted] error", e);
      } finally {
        setLoading(false);
      }
    },
    [initParams.user_id, initParams.xsec_source, initParams.xsec_token]
  );

  const loadMore = useCallback(() => {
    if (!hasMore || loading) return;
    fetchPosted(false, cursorRef.current);
  }, [fetchPosted, hasMore, loading]);

  useEffect(() => {
    if (open) {
      const firstCursor = initParams.cursor || "";
      setItems([]);
      setCursor(firstCursor);
      cursorRef.current = firstCursor;
      setHasMore(true);
      fetchPosted(true, firstCursor);
      fetchHover();
    } else {
      setItems([]);
      setCursor("");
      cursorRef.current = "";
      setHasMore(true);
      setHoverData(null);
      setHoverError(null);
    }
    // 仅在 open 或 initParams 关键字段变化时触发，不添加 fetchPosted 以避免重复请求
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, initParams.cursor, initParams.user_id, initParams.xsec_token]);

  const isFollowed = hoverData?.extraInfo_info?.fstatus && hoverData.extraInfo_info.fstatus !== 'none';
  const follows = hoverData?.interact_info?.follows || '0';
  const fans = hoverData?.interact_info?.fans || '0';
  const interaction = hoverData?.interact_info?.interaction || '0';
  const desc = hoverData?.basic_info?.desc || '';
  const handleFollowClick = () => {
    if (!isFollowed) {
      messageApi.info('暂未实现关注接口');
    } else {
      messageApi.info('暂未实现取消关注接口');
    }
  };

  return (
    <Drawer
      open={open}
      onClose={onClose}
      placement="bottom"
      destroyOnHidden
      height="90vh"
      title={`用户主页 - ${nickname}`}
      styles={{
        body: { padding: 0, height: "100%", overflow: "auto" },
      }}
    >
      {contextHolder}
      <div style={{ padding: 16 }}>
        {/* 用户详情区（微博风格） */}
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16, marginBottom: 12 }}>
          <Avatar src={avatar} size={80}>{nickname[0]}</Avatar>
          <div style={{ fontSize: 20, fontWeight: 'bolder' }}>{nickname}</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center' }}>
            {hoverLoading && <Tag color="default">加载用户信息...</Tag>}
            {hoverError && <Tag color="red">{hoverError}</Tag>}
            {!hoverLoading && !hoverError && hoverData && (
              <>
                <Tag icon={<UsergroupAddOutlined />} color="green">关注: {follows}</Tag>
                <Tag icon={<TeamOutlined />} color="orange">粉丝: {fans}</Tag>
                <Tag icon={<LikeOutlined />} color="magenta">获赞收藏: {interaction}</Tag>
              </>
            )}
          </div>
          {!hoverLoading && !hoverError && desc && (
            <Card size="small" styles={{ body: { padding: '10px', textAlign: 'center' } }}>{desc}</Card>
          )}
          {!hoverLoading && !hoverError && initParams.user_id && (
            isFollowed ? (
              <Button color="red" variant="filled" onClick={handleFollowClick}>取关</Button>
            ) : (
              <Button color="primary" variant="filled" onClick={handleFollowClick}>关注</Button>
            )
          )}
        </div>
        {/* 瀑布流 */}
        {loading && items.length === 0 ? (
          loaderFunc()
        ) : items.length > 0 ? (
          <Masonry
            breakpointCols={{
              default: 2,
              1500: 5,
              1200: 4,
              9000: 3,
              600: 2,
              300: 1,
            }}
            className="xhs-masonry"
            columnClassName="xhs-masonry-column"
          >
            {items.map((raw: any, index: number) => (
              <div
                key={raw.id + index}
                className="xhs-waterfall-item"
                style={{ animationDelay: `${(index % 10) * 50}ms` }}
              >
                <XhsFeedCard
                  data={raw}
                  onClick={() => onOpenDetail?.(raw)}
                  onUserClick={() => {
                    // 已在当前用户主页
                    messageApi.info("已经是本用户主页了");
                  }}
                />
              </div>
            ))}
          </Masonry>
        ) : (
          <Empty
            description="暂无用户笔记"
            image={Empty.PRESENTED_IMAGE_SIMPLE}
          />
        )}
        {hasMore && !loading && items.length > 0 && (
          <div style={{ textAlign: "center", padding: 12 }}>
            <Button
              variant="filled"
              color="default"
              loading={loading}
              onClick={loadMore}
            >
              {loading ? "加载中..." : "加载更多"}
            </Button>
          </div>
        )}
      </div>
    </Drawer>
  );
};

export default UserPostedDrawer;
