/*
 * @Author: Generated by Copilot
 * @Date: 2025-11-03
 * @Description: 小红书用户主页 Drawer：展示用户头像/昵称及其已发布笔记瀑布流，可翻页加载。
 */
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Drawer, Avatar, Card, Button, Empty } from "antd";
import Masonry from "react-masonry-css";
import { createXhsApi } from "../api";
import { useRequest } from "../hooks/useRequest";
import XhsFeedCard from "./XhsFeedCard";
import { loaderFunc } from "../utils/loader";
import { XhsFeedRawItem } from "../../../type";

interface UserPostedDrawerProps {
  open: boolean;
  onClose: () => void;
  // 初始参数：从点击的笔记中获取 note id 作为 cursor（或空字符串），以及 user 对象里的 user_id 与 xsec_token
  initParams: {
    cursor: string;
    user_id: string;
    xsec_token: string;
    user?: any;
  };
}

const UserPostedDrawer: React.FC<UserPostedDrawerProps> = ({
  open,
  onClose,
  initParams,
}) => {
  const { request } = useRequest();
  const apiRef = useRef(createXhsApi(request));

  const [loading, setLoading] = useState(false);
  const [cursor, setCursor] = useState(initParams.cursor);
  const [items, setItems] = useState<XhsFeedRawItem[]>([]);
  const [hasMore, setHasMore] = useState(true);
  // 使用 ref 保存最新 cursor，避免将 cursor 纳入 useCallback 依赖导致函数重建和二次请求
  const cursorRef = useRef(cursor);

  // 用户信息基础展示
  const user = initParams.user || {}; // 兼容从 note_card.user 传入
  const nickname: string = user.nick_name || user.nickname || "未知用户";
  const avatar: string | undefined = user.avatar;

  const fetchPosted = useCallback(
    async (reset: boolean = false, nextCursor?: string) => {
      if (!initParams.user_id || !initParams.xsec_token) return;
      const useCursor = reset ? (nextCursor ?? "") : (nextCursor ?? cursorRef.current);
      setLoading(true);
      try {
        const res: any = await apiRef.current.getUserPosted({
          user_id: initParams.user_id,
          cursor: useCursor,
          xsec_token: initParams.xsec_token,
        });
        const incoming: XhsFeedRawItem[] = res?.items || [];
        setItems((prev) => (reset ? incoming : [...prev, ...incoming]));
        const newCursor = res?.cursor || "";
        setCursor(newCursor);
        cursorRef.current = newCursor; // 同步 ref
        setHasMore(!!res?.has_more);
      } catch (e) {
        console.error("[xhs user posted] error", e);
      } finally {
        setLoading(false);
      }
    },
    [apiRef, initParams.user_id, initParams.xsec_token]
  );

  const loadMore = useCallback(() => {
    if (!hasMore || loading) return;
    fetchPosted(false, cursorRef.current);
  }, [fetchPosted, hasMore, loading]);

  useEffect(() => {
    if (open) {
      const firstCursor = initParams.cursor || "";
      setItems([]);
      setCursor(firstCursor);
      cursorRef.current = firstCursor;
      setHasMore(true);
      fetchPosted(true, firstCursor);
    } else {
      setItems([]);
      setCursor("");
      cursorRef.current = "";
      setHasMore(true);
    }
    // 仅在 open 或 initParams 关键字段变化时触发，不添加 fetchPosted 以避免重复请求
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, initParams.cursor, initParams.user_id, initParams.xsec_token]);

  const handleUserClick = useCallback(() => {
    // 点击头像刷新用户主页
    fetchPosted(true, "");
  }, [fetchPosted]);

  return (
    <Drawer
      open={open}
      onClose={onClose}
      placement="bottom"
      destroyOnHidden
      height="90vh"
      title={`用户主页 - ${nickname}`}
      styles={{
        body: { padding: 0, height: "100%", overflow: "auto" },
      }}
    >
      <div style={{ padding: 16 }}>
        <Card size="small" style={{ marginBottom: 12 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <Avatar src={avatar} size={48} onClick={handleUserClick}>
              {nickname[0]}
            </Avatar>
            <div style={{ fontWeight: 600, fontSize: 20 }}>{nickname}</div>
          </div>
        </Card>
        {/* 瀑布流 */}
        {loading && items.length === 0 ? (
          loaderFunc()
        ) : items.length > 0 ? (
          <Masonry
            breakpointCols={{
              default: 2,
              1500: 5,
              1200: 4,
              9000: 3,
              600: 2,
              300: 1,
            }}
            className="xhs-masonry"
            columnClassName="xhs-masonry-column"
          >
            {items.map((raw: any, index: number) => (
              <div
                key={raw.id + index}
                className="xhs-waterfall-item"
                style={{ animationDelay: `${(index % 10) * 50}ms` }}
              >
                <XhsFeedCard
                  data={raw}
                  onClick={() => {
                    /* 复用外部 FeedDetailDrawer 由父层处理 */
                  }}
                />
              </div>
            ))}
          </Masonry>
        ) : (
          <Empty
            description="暂无用户笔记"
            image={Empty.PRESENTED_IMAGE_SIMPLE}
          />
        )}
        {hasMore && !loading && items.length > 0 && (
          <div style={{ textAlign: "center", padding: 12 }}>
            <Button
              variant="filled"
              color="default"
              loading={loading}
              onClick={loadMore}
            >
              {loading ? "加载中..." : "加载更多"}
            </Button>
          </div>
        )}
      </div>
    </Drawer>
  );
};

export default UserPostedDrawer;
